### ISSUE TITLE
One model not authorizing access 

### ISSUE THREAD

**Issue by Areeeb** [narainsagar/ama#1]
I have 7 models.
Comments
Connections
Likes 
Shares
Post
User [This model is by default from loopback.io]
users

All models are successfully getting and posting data except that users model, its not authorizing me. I haven't set anything but don't know why its not allowing me.

**Comment by narainsagar** [comment]
Hi @Areeeb If you've generated your backend codebase and REST API using [loopback-cli](http://loopback.io/getting-started/) then It have default created `User` model and it's routes.

Loopback-cli will have default enabled authorization on all `User` routes so you can't access them without login and you can set them by setting up access token in api explorer.

fyi. When you start `serve` your backend and open the api in browser tab with tab suffix `http://0.0.0.0:3000/explorer` you'll see all api documentation.

**Comment by narainsagar** [comment]
@Areeeb Here's example screenshot attached for how *API explorer* will be look like.. 

- You'll see `acessToken` inputbox and `Set Access Token ` button; you need to set access token to access the `/user` routes (in your case)

<img src="http://loopback.io/images/overview/helloworld-api-explorer.png" />
