### ISSUE TITLE
What if i want to make http get request in index.html page

### ISSUE THREAD

**Issue by Areeeb** [narainsagar/ama#2]
I am including cover page as index page of my website. There would be login and logout buttons and signup button on that page which means user's sign in would validate from mongodb at that index.html page. So how do i make that request. There is no typescript file (.ts) file for index.html.

**Comment by narainsagar** [comment]
Better would be if you can create new component and move the required index.html code there and make http calls there from component.

if you still want to do in index.html then you can use jquery ajax to make http calls etc.
