### ISSUE TITLE
Passing variable from app.component.ts to social.component.ts

### ISSUE THREAD

**Issue by Areeeb** [narainsagar/ama#3]
I want to pass 2 to 3 variables from app.component.ts to social.component.ts . I have searched a lot but couldn't find the answer. Please help me out.

**Comment by narainsagar** [comment]
Hi @Areeeb You can use angular `@Input` decorator to pass data from parent component to child component and if you want to send data from child component to parent component you can use `@Output` decorator

Here're few tutorials / resources; you can look:
- https://angular.io/guide/component-interaction
- https://developer.telerik.com/topics/web-development/component-property-binding-input-angular-2/
- https://toddmotto.com/passing-data-angular-2-components-input
- https://www.sitepoint.com/angular-2-components-inputs-outputs/
- https://angular-2-training-book.rangle.io/handout/components/app_structure/passing_data_into_components.html

**Comment by Areeeb** [comment]
No, I want to pass data actually to the component that are called by routing, i.e. they are call by <router-outlet> directive.

**Comment by narainsagar** [comment]
you can use `EventEmitter` in that case. you need to emit the data from parent component and subscribe on EventEmitter instance in child component.
