### ISSUE TITLE
Getting response from post request

### ISSUE THREAD

**Issue by Areeeb** [narainsagar/ama#4]
I am posting username and password to /users/login. How do i get the response code in return so that i could proceed?

**Comment by narainsagar** [comment]
see this for http and post call example in angular2+: https://angular.io/guide/http#making-a-post-request

I'm not sure, what you exactly mean by "response code" here.. But I think this might help. Thanks.

might be related to this: https://stackoverflow.com/questions/42003304/how-to-get-status-code-in-http-request-in-angular2

with angular2+, for what I know, if our request will be successful then in `subscribe` success callback will be executed and it will return response there else it will execute error callback you the error will contain the status code.. 

so, you don't have to worry and check status code for success request.. But you can get status code for failing requests.

Here's example code will look like:
```
http.post('/api/items/add', body).subscribe((res) => {
   console.log('success callback.');
   console.log('response', res);
}, (err) => {
   console.log('error callback.');
   console.log('error', err);
})
```
